run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - typecheck
  disable-all: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/tarungka/wire

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude:
    - "Error return value of .((Close|Write).*) is not checked"
    - "SA1019:" # Deprecated function usage