// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: command.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest_Level int32

const (
	QueryRequest_QUERY_REQUEST_LEVEL_NONE   QueryRequest_Level = 0
	QueryRequest_QUERY_REQUEST_LEVEL_WEAK   QueryRequest_Level = 1
	QueryRequest_QUERY_REQUEST_LEVEL_STRONG QueryRequest_Level = 2
	QueryRequest_QUERY_REQUEST_LEVEL_AUTO   QueryRequest_Level = 3
)

// Enum value maps for QueryRequest_Level.
var (
	QueryRequest_Level_name = map[int32]string{
		0: "QUERY_REQUEST_LEVEL_NONE",
		1: "QUERY_REQUEST_LEVEL_WEAK",
		2: "QUERY_REQUEST_LEVEL_STRONG",
		3: "QUERY_REQUEST_LEVEL_AUTO",
	}
	QueryRequest_Level_value = map[string]int32{
		"QUERY_REQUEST_LEVEL_NONE":   0,
		"QUERY_REQUEST_LEVEL_WEAK":   1,
		"QUERY_REQUEST_LEVEL_STRONG": 2,
		"QUERY_REQUEST_LEVEL_AUTO":   3,
	}
)

func (x QueryRequest_Level) Enum() *QueryRequest_Level {
	p := new(QueryRequest_Level)
	*p = x
	return p
}

func (x QueryRequest_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryRequest_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[0].Descriptor()
}

func (QueryRequest_Level) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[0]
}

func (x QueryRequest_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryRequest_Level.Descriptor instead.
func (QueryRequest_Level) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3, 0}
}

type BackupRequest_Format int32

const (
	BackupRequest_BACKUP_REQUEST_FORMAT_NONE   BackupRequest_Format = 0
	BackupRequest_BACKUP_REQUEST_FORMAT_SQL    BackupRequest_Format = 1
	BackupRequest_BACKUP_REQUEST_FORMAT_BINARY BackupRequest_Format = 2
)

// Enum value maps for BackupRequest_Format.
var (
	BackupRequest_Format_name = map[int32]string{
		0: "BACKUP_REQUEST_FORMAT_NONE",
		1: "BACKUP_REQUEST_FORMAT_SQL",
		2: "BACKUP_REQUEST_FORMAT_BINARY",
	}
	BackupRequest_Format_value = map[string]int32{
		"BACKUP_REQUEST_FORMAT_NONE":   0,
		"BACKUP_REQUEST_FORMAT_SQL":    1,
		"BACKUP_REQUEST_FORMAT_BINARY": 2,
	}
)

func (x BackupRequest_Format) Enum() *BackupRequest_Format {
	p := new(BackupRequest_Format)
	*p = x
	return p
}

func (x BackupRequest_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BackupRequest_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[1].Descriptor()
}

func (BackupRequest_Format) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[1]
}

func (x BackupRequest_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BackupRequest_Format.Descriptor instead.
func (BackupRequest_Format) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{10, 0}
}

type Command_Type int32

const (
	Command_COMMAND_TYPE_UNKNOWN       Command_Type = 0
	Command_COMMAND_TYPE_QUERY         Command_Type = 1
	Command_COMMAND_TYPE_EXECUTE       Command_Type = 2
	Command_COMMAND_TYPE_NOOP          Command_Type = 3
	Command_COMMAND_TYPE_LOAD          Command_Type = 4
	Command_COMMAND_TYPE_JOIN          Command_Type = 5
	Command_COMMAND_TYPE_EXECUTE_QUERY Command_Type = 6
	Command_COMMAND_TYPE_LOAD_CHUNK    Command_Type = 7
)

// Enum value maps for Command_Type.
var (
	Command_Type_name = map[int32]string{
		0: "COMMAND_TYPE_UNKNOWN",
		1: "COMMAND_TYPE_QUERY",
		2: "COMMAND_TYPE_EXECUTE",
		3: "COMMAND_TYPE_NOOP",
		4: "COMMAND_TYPE_LOAD",
		5: "COMMAND_TYPE_JOIN",
		6: "COMMAND_TYPE_EXECUTE_QUERY",
		7: "COMMAND_TYPE_LOAD_CHUNK",
	}
	Command_Type_value = map[string]int32{
		"COMMAND_TYPE_UNKNOWN":       0,
		"COMMAND_TYPE_QUERY":         1,
		"COMMAND_TYPE_EXECUTE":       2,
		"COMMAND_TYPE_NOOP":          3,
		"COMMAND_TYPE_LOAD":          4,
		"COMMAND_TYPE_JOIN":          5,
		"COMMAND_TYPE_EXECUTE_QUERY": 6,
		"COMMAND_TYPE_LOAD_CHUNK":    7,
	}
)

func (x Command_Type) Enum() *Command_Type {
	p := new(Command_Type)
	*p = x
	return p
}

func (x Command_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_command_proto_enumTypes[2].Descriptor()
}

func (Command_Type) Type() protoreflect.EnumType {
	return &file_command_proto_enumTypes[2]
}

func (x Command_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Type.Descriptor instead.
func (Command_Type) EnumDescriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{17, 0}
}

type Parameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Parameter_I
	//	*Parameter_D
	//	*Parameter_B
	//	*Parameter_Y
	//	*Parameter_S
	Value         isParameter_Value `protobuf_oneof:"value"`
	Name          string            `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{0}
}

func (x *Parameter) GetValue() isParameter_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Parameter) GetI() int64 {
	if x != nil {
		if x, ok := x.Value.(*Parameter_I); ok {
			return x.I
		}
	}
	return 0
}

func (x *Parameter) GetD() float64 {
	if x != nil {
		if x, ok := x.Value.(*Parameter_D); ok {
			return x.D
		}
	}
	return 0
}

func (x *Parameter) GetB() bool {
	if x != nil {
		if x, ok := x.Value.(*Parameter_B); ok {
			return x.B
		}
	}
	return false
}

func (x *Parameter) GetY() []byte {
	if x != nil {
		if x, ok := x.Value.(*Parameter_Y); ok {
			return x.Y
		}
	}
	return nil
}

func (x *Parameter) GetS() string {
	if x != nil {
		if x, ok := x.Value.(*Parameter_S); ok {
			return x.S
		}
	}
	return ""
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type isParameter_Value interface {
	isParameter_Value()
}

type Parameter_I struct {
	I int64 `protobuf:"zigzag64,1,opt,name=i,proto3,oneof"`
}

type Parameter_D struct {
	D float64 `protobuf:"fixed64,2,opt,name=d,proto3,oneof"`
}

type Parameter_B struct {
	B bool `protobuf:"varint,3,opt,name=b,proto3,oneof"`
}

type Parameter_Y struct {
	Y []byte `protobuf:"bytes,4,opt,name=y,proto3,oneof"`
}

type Parameter_S struct {
	S string `protobuf:"bytes,5,opt,name=s,proto3,oneof"`
}

func (*Parameter_I) isParameter_Value() {}

func (*Parameter_D) isParameter_Value() {}

func (*Parameter_B) isParameter_Value() {}

func (*Parameter_Y) isParameter_Value() {}

func (*Parameter_S) isParameter_Value() {}

type Statement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Parameters    []*Parameter           `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	ForceQuery    bool                   `protobuf:"varint,3,opt,name=forceQuery,proto3" json:"forceQuery,omitempty"` // not really used as of now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statement) Reset() {
	*x = Statement{}
	mi := &file_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statement) ProtoMessage() {}

func (x *Statement) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statement.ProtoReflect.Descriptor instead.
func (*Statement) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{1}
}

func (x *Statement) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *Statement) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Statement) GetForceQuery() bool {
	if x != nil {
		return x.ForceQuery
	}
	return false
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   bool                   `protobuf:"varint,1,opt,name=transaction,proto3" json:"transaction,omitempty"` // if a transaction
	Statements    []*Statement           `protobuf:"bytes,2,rep,name=statements,proto3" json:"statements,omitempty"`    // the statement/command
	DbTimeout     int64                  `protobuf:"varint,3,opt,name=dbTimeout,proto3" json:"dbTimeout,omitempty"`     // timeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetTransaction() bool {
	if x != nil {
		return x.Transaction
	}
	return false
}

func (x *Request) GetStatements() []*Statement {
	if x != nil {
		return x.Statements
	}
	return nil
}

func (x *Request) GetDbTimeout() int64 {
	if x != nil {
		return x.DbTimeout
	}
	return 0
}

type QueryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Request         *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Timings         bool                   `protobuf:"varint,2,opt,name=timings,proto3" json:"timings,omitempty"`
	Level           QueryRequest_Level     `protobuf:"varint,3,opt,name=level,proto3,enum=command.QueryRequest_Level" json:"level,omitempty"`
	Freshness       int64                  `protobuf:"varint,4,opt,name=freshness,proto3" json:"freshness,omitempty"`
	FreshnessStrict bool                   `protobuf:"varint,5,opt,name=freshness_strict,json=freshnessStrict,proto3" json:"freshness_strict,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{3}
}

func (x *QueryRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *QueryRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

func (x *QueryRequest) GetLevel() QueryRequest_Level {
	if x != nil {
		return x.Level
	}
	return QueryRequest_QUERY_REQUEST_LEVEL_NONE
}

func (x *QueryRequest) GetFreshness() int64 {
	if x != nil {
		return x.Freshness
	}
	return 0
}

func (x *QueryRequest) GetFreshnessStrict() bool {
	if x != nil {
		return x.FreshnessStrict
	}
	return false
}

type Values struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*Parameter           `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Values) Reset() {
	*x = Values{}
	mi := &file_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Values) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Values) ProtoMessage() {}

func (x *Values) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Values.ProtoReflect.Descriptor instead.
func (*Values) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{4}
}

func (x *Values) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type QueryRows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Types         []string               `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	Values        []*Values              `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Time          float64                `protobuf:"fixed64,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRows) Reset() {
	*x = QueryRows{}
	mi := &file_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRows) ProtoMessage() {}

func (x *QueryRows) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRows.ProtoReflect.Descriptor instead.
func (*QueryRows) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{5}
}

func (x *QueryRows) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryRows) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *QueryRows) GetValues() []*Values {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *QueryRows) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryRows) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Timings       bool                   `protobuf:"varint,2,opt,name=timings,proto3" json:"timings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecuteRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

type ExecuteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastInsertId  int64                  `protobuf:"varint,1,opt,name=last_insert_id,json=lastInsertId,proto3" json:"last_insert_id,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Time          float64                `protobuf:"fixed64,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResult) Reset() {
	*x = ExecuteResult{}
	mi := &file_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResult) ProtoMessage() {}

func (x *ExecuteResult) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResult.ProtoReflect.Descriptor instead.
func (*ExecuteResult) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResult) GetLastInsertId() int64 {
	if x != nil {
		return x.LastInsertId
	}
	return 0
}

func (x *ExecuteResult) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *ExecuteResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResult) GetTime() float64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ExecuteQueryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Request         *Request               `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Timings         bool                   `protobuf:"varint,2,opt,name=timings,proto3" json:"timings,omitempty"`
	Level           QueryRequest_Level     `protobuf:"varint,3,opt,name=level,proto3,enum=command.QueryRequest_Level" json:"level,omitempty"`
	Freshness       int64                  `protobuf:"varint,4,opt,name=freshness,proto3" json:"freshness,omitempty"`
	FreshnessStrict bool                   `protobuf:"varint,5,opt,name=freshness_strict,json=freshnessStrict,proto3" json:"freshness_strict,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteQueryRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ExecuteQueryRequest) GetTimings() bool {
	if x != nil {
		return x.Timings
	}
	return false
}

func (x *ExecuteQueryRequest) GetLevel() QueryRequest_Level {
	if x != nil {
		return x.Level
	}
	return QueryRequest_QUERY_REQUEST_LEVEL_NONE
}

func (x *ExecuteQueryRequest) GetFreshness() int64 {
	if x != nil {
		return x.Freshness
	}
	return 0
}

func (x *ExecuteQueryRequest) GetFreshnessStrict() bool {
	if x != nil {
		return x.FreshnessStrict
	}
	return false
}

type ExecuteQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteQueryResponse_Q
	//	*ExecuteQueryResponse_E
	//	*ExecuteQueryResponse_Error
	Result        isExecuteQueryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteQueryResponse) GetResult() isExecuteQueryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteQueryResponse) GetQ() *QueryRows {
	if x != nil {
		if x, ok := x.Result.(*ExecuteQueryResponse_Q); ok {
			return x.Q
		}
	}
	return nil
}

func (x *ExecuteQueryResponse) GetE() *ExecuteResult {
	if x != nil {
		if x, ok := x.Result.(*ExecuteQueryResponse_E); ok {
			return x.E
		}
	}
	return nil
}

func (x *ExecuteQueryResponse) GetError() string {
	if x != nil {
		if x, ok := x.Result.(*ExecuteQueryResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isExecuteQueryResponse_Result interface {
	isExecuteQueryResponse_Result()
}

type ExecuteQueryResponse_Q struct {
	Q *QueryRows `protobuf:"bytes,1,opt,name=q,proto3,oneof"`
}

type ExecuteQueryResponse_E struct {
	E *ExecuteResult `protobuf:"bytes,2,opt,name=e,proto3,oneof"`
}

type ExecuteQueryResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*ExecuteQueryResponse_Q) isExecuteQueryResponse_Result() {}

func (*ExecuteQueryResponse_E) isExecuteQueryResponse_Result() {}

func (*ExecuteQueryResponse_Error) isExecuteQueryResponse_Result() {}

type BackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        BackupRequest_Format   `protobuf:"varint,1,opt,name=format,proto3,enum=command.BackupRequest_Format" json:"format,omitempty"`
	Leader        bool                   `protobuf:"varint,2,opt,name=Leader,proto3" json:"Leader,omitempty"`
	Vacuum        bool                   `protobuf:"varint,3,opt,name=Vacuum,proto3" json:"Vacuum,omitempty"`
	Compress      bool                   `protobuf:"varint,4,opt,name=Compress,proto3" json:"Compress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupRequest) Reset() {
	*x = BackupRequest{}
	mi := &file_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupRequest) ProtoMessage() {}

func (x *BackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupRequest.ProtoReflect.Descriptor instead.
func (*BackupRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{10}
}

func (x *BackupRequest) GetFormat() BackupRequest_Format {
	if x != nil {
		return x.Format
	}
	return BackupRequest_BACKUP_REQUEST_FORMAT_NONE
}

func (x *BackupRequest) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

func (x *BackupRequest) GetVacuum() bool {
	if x != nil {
		return x.Vacuum
	}
	return false
}

func (x *BackupRequest) GetCompress() bool {
	if x != nil {
		return x.Compress
	}
	return false
}

type LoadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadRequest) Reset() {
	*x = LoadRequest{}
	mi := &file_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadRequest) ProtoMessage() {}

func (x *LoadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadRequest.ProtoReflect.Descriptor instead.
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{11}
}

func (x *LoadRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoadChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	SequenceNum   int64                  `protobuf:"varint,2,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Abort         bool                   `protobuf:"varint,5,opt,name=abort,proto3" json:"abort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadChunkRequest) Reset() {
	*x = LoadChunkRequest{}
	mi := &file_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadChunkRequest) ProtoMessage() {}

func (x *LoadChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadChunkRequest.ProtoReflect.Descriptor instead.
func (*LoadChunkRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{12}
}

func (x *LoadChunkRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LoadChunkRequest) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *LoadChunkRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *LoadChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LoadChunkRequest) GetAbort() bool {
	if x != nil {
		return x.Abort
	}
	return false
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Voter         bool                   `protobuf:"varint,3,opt,name=voter,proto3" json:"voter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRequest) GetVoter() bool {
	if x != nil {
		return x.Voter
	}
	return false
}

type NotifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_command_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Noop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Noop) Reset() {
	*x = Noop{}
	mi := &file_command_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{16}
}

func (x *Noop) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Command_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=command.Command_Type" json:"type,omitempty"`
	SubCommand    []byte                 `protobuf:"bytes,2,opt,name=sub_command,json=subCommand,proto3" json:"sub_command,omitempty"`
	Compressed    bool                   `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_proto_rawDescGZIP(), []int{17}
}

func (x *Command) GetType() Command_Type {
	if x != nil {
		return x.Type
	}
	return Command_COMMAND_TYPE_UNKNOWN
}

func (x *Command) GetSubCommand() []byte {
	if x != nil {
		return x.SubCommand
	}
	return nil
}

func (x *Command) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

var File_command_proto protoreflect.FileDescriptor

const file_command_proto_rawDesc = "" +
	"\n" +
	"\rcommand.proto\x12\acommand\"x\n" +
	"\tParameter\x12\x0e\n" +
	"\x01i\x18\x01 \x01(\x12H\x00R\x01i\x12\x0e\n" +
	"\x01d\x18\x02 \x01(\x01H\x00R\x01d\x12\x0e\n" +
	"\x01b\x18\x03 \x01(\bH\x00R\x01b\x12\x0e\n" +
	"\x01y\x18\x04 \x01(\fH\x00R\x01y\x12\x0e\n" +
	"\x01s\x18\x05 \x01(\tH\x00R\x01s\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04nameB\a\n" +
	"\x05value\"q\n" +
	"\tStatement\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x122\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2\x12.command.ParameterR\n" +
	"parameters\x12\x1e\n" +
	"\n" +
	"forceQuery\x18\x03 \x01(\bR\n" +
	"forceQuery\"}\n" +
	"\aRequest\x12 \n" +
	"\vtransaction\x18\x01 \x01(\bR\vtransaction\x122\n" +
	"\n" +
	"statements\x18\x02 \x03(\v2\x12.command.StatementR\n" +
	"statements\x12\x1c\n" +
	"\tdbTimeout\x18\x03 \x01(\x03R\tdbTimeout\"\xd4\x02\n" +
	"\fQueryRequest\x12*\n" +
	"\arequest\x18\x01 \x01(\v2\x10.command.RequestR\arequest\x12\x18\n" +
	"\atimings\x18\x02 \x01(\bR\atimings\x121\n" +
	"\x05level\x18\x03 \x01(\x0e2\x1b.command.QueryRequest.LevelR\x05level\x12\x1c\n" +
	"\tfreshness\x18\x04 \x01(\x03R\tfreshness\x12)\n" +
	"\x10freshness_strict\x18\x05 \x01(\bR\x0ffreshnessStrict\"\x81\x01\n" +
	"\x05Level\x12\x1c\n" +
	"\x18QUERY_REQUEST_LEVEL_NONE\x10\x00\x12\x1c\n" +
	"\x18QUERY_REQUEST_LEVEL_WEAK\x10\x01\x12\x1e\n" +
	"\x1aQUERY_REQUEST_LEVEL_STRONG\x10\x02\x12\x1c\n" +
	"\x18QUERY_REQUEST_LEVEL_AUTO\x10\x03\"<\n" +
	"\x06Values\x122\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x12.command.ParameterR\n" +
	"parameters\"\x8e\x01\n" +
	"\tQueryRows\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types\x12'\n" +
	"\x06values\x18\x03 \x03(\v2\x0f.command.ValuesR\x06values\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x01R\x04time\"V\n" +
	"\x0eExecuteRequest\x12*\n" +
	"\arequest\x18\x01 \x01(\v2\x10.command.RequestR\arequest\x12\x18\n" +
	"\atimings\x18\x02 \x01(\bR\atimings\"\x84\x01\n" +
	"\rExecuteResult\x12$\n" +
	"\x0elast_insert_id\x18\x01 \x01(\x03R\flastInsertId\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x03R\frowsAffected\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x01R\x04time\"\xd7\x01\n" +
	"\x13ExecuteQueryRequest\x12*\n" +
	"\arequest\x18\x01 \x01(\v2\x10.command.RequestR\arequest\x12\x18\n" +
	"\atimings\x18\x02 \x01(\bR\atimings\x121\n" +
	"\x05level\x18\x03 \x01(\x0e2\x1b.command.QueryRequest.LevelR\x05level\x12\x1c\n" +
	"\tfreshness\x18\x04 \x01(\x03R\tfreshness\x12)\n" +
	"\x10freshness_strict\x18\x05 \x01(\bR\x0ffreshnessStrict\"\x84\x01\n" +
	"\x14ExecuteQueryResponse\x12\"\n" +
	"\x01q\x18\x01 \x01(\v2\x12.command.QueryRowsH\x00R\x01q\x12&\n" +
	"\x01e\x18\x02 \x01(\v2\x16.command.ExecuteResultH\x00R\x01e\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06result\"\xfd\x01\n" +
	"\rBackupRequest\x125\n" +
	"\x06format\x18\x01 \x01(\x0e2\x1d.command.BackupRequest.FormatR\x06format\x12\x16\n" +
	"\x06Leader\x18\x02 \x01(\bR\x06Leader\x12\x16\n" +
	"\x06Vacuum\x18\x03 \x01(\bR\x06Vacuum\x12\x1a\n" +
	"\bCompress\x18\x04 \x01(\bR\bCompress\"i\n" +
	"\x06Format\x12\x1e\n" +
	"\x1aBACKUP_REQUEST_FORMAT_NONE\x10\x00\x12\x1d\n" +
	"\x19BACKUP_REQUEST_FORMAT_SQL\x10\x01\x12 \n" +
	"\x1cBACKUP_REQUEST_FORMAT_BINARY\x10\x02\"!\n" +
	"\vLoadRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x95\x01\n" +
	"\x10LoadChunkRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\fsequence_num\x18\x02 \x01(\x03R\vsequenceNum\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x14\n" +
	"\x05abort\x18\x05 \x01(\bR\x05abort\"M\n" +
	"\vJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x14\n" +
	"\x05voter\x18\x03 \x01(\bR\x05voter\"9\n" +
	"\rNotifyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"#\n" +
	"\x11RemoveNodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x04Noop\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcc\x02\n" +
	"\aCommand\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.command.Command.TypeR\x04type\x12\x1f\n" +
	"\vsub_command\x18\x02 \x01(\fR\n" +
	"subCommand\x12\x1e\n" +
	"\n" +
	"compressed\x18\x03 \x01(\bR\n" +
	"compressed\"\xd4\x01\n" +
	"\x04Type\x12\x18\n" +
	"\x14COMMAND_TYPE_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12COMMAND_TYPE_QUERY\x10\x01\x12\x18\n" +
	"\x14COMMAND_TYPE_EXECUTE\x10\x02\x12\x15\n" +
	"\x11COMMAND_TYPE_NOOP\x10\x03\x12\x15\n" +
	"\x11COMMAND_TYPE_LOAD\x10\x04\x12\x15\n" +
	"\x11COMMAND_TYPE_JOIN\x10\x05\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_EXECUTE_QUERY\x10\x06\x12\x1b\n" +
	"\x17COMMAND_TYPE_LOAD_CHUNK\x10\aB1Z/github.com/tarungka/wire/internal/command/protob\x06proto3"

var (
	file_command_proto_rawDescOnce sync.Once
	file_command_proto_rawDescData []byte
)

func file_command_proto_rawDescGZIP() []byte {
	file_command_proto_rawDescOnce.Do(func() {
		file_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)))
	})
	return file_command_proto_rawDescData
}

var file_command_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_command_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_command_proto_goTypes = []any{
	(QueryRequest_Level)(0),      // 0: command.QueryRequest.Level
	(BackupRequest_Format)(0),    // 1: command.BackupRequest.Format
	(Command_Type)(0),            // 2: command.Command.Type
	(*Parameter)(nil),            // 3: command.Parameter
	(*Statement)(nil),            // 4: command.Statement
	(*Request)(nil),              // 5: command.Request
	(*QueryRequest)(nil),         // 6: command.QueryRequest
	(*Values)(nil),               // 7: command.Values
	(*QueryRows)(nil),            // 8: command.QueryRows
	(*ExecuteRequest)(nil),       // 9: command.ExecuteRequest
	(*ExecuteResult)(nil),        // 10: command.ExecuteResult
	(*ExecuteQueryRequest)(nil),  // 11: command.ExecuteQueryRequest
	(*ExecuteQueryResponse)(nil), // 12: command.ExecuteQueryResponse
	(*BackupRequest)(nil),        // 13: command.BackupRequest
	(*LoadRequest)(nil),          // 14: command.LoadRequest
	(*LoadChunkRequest)(nil),     // 15: command.LoadChunkRequest
	(*JoinRequest)(nil),          // 16: command.JoinRequest
	(*NotifyRequest)(nil),        // 17: command.NotifyRequest
	(*RemoveNodeRequest)(nil),    // 18: command.RemoveNodeRequest
	(*Noop)(nil),                 // 19: command.Noop
	(*Command)(nil),              // 20: command.Command
}
var file_command_proto_depIdxs = []int32{
	3,  // 0: command.Statement.parameters:type_name -> command.Parameter
	4,  // 1: command.Request.statements:type_name -> command.Statement
	5,  // 2: command.QueryRequest.request:type_name -> command.Request
	0,  // 3: command.QueryRequest.level:type_name -> command.QueryRequest.Level
	3,  // 4: command.Values.parameters:type_name -> command.Parameter
	7,  // 5: command.QueryRows.values:type_name -> command.Values
	5,  // 6: command.ExecuteRequest.request:type_name -> command.Request
	5,  // 7: command.ExecuteQueryRequest.request:type_name -> command.Request
	0,  // 8: command.ExecuteQueryRequest.level:type_name -> command.QueryRequest.Level
	8,  // 9: command.ExecuteQueryResponse.q:type_name -> command.QueryRows
	10, // 10: command.ExecuteQueryResponse.e:type_name -> command.ExecuteResult
	1,  // 11: command.BackupRequest.format:type_name -> command.BackupRequest.Format
	2,  // 12: command.Command.type:type_name -> command.Command.Type
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_command_proto_init() }
func file_command_proto_init() {
	if File_command_proto != nil {
		return
	}
	file_command_proto_msgTypes[0].OneofWrappers = []any{
		(*Parameter_I)(nil),
		(*Parameter_D)(nil),
		(*Parameter_B)(nil),
		(*Parameter_Y)(nil),
		(*Parameter_S)(nil),
	}
	file_command_proto_msgTypes[9].OneofWrappers = []any{
		(*ExecuteQueryResponse_Q)(nil),
		(*ExecuteQueryResponse_E)(nil),
		(*ExecuteQueryResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_proto_rawDesc), len(file_command_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_proto_goTypes,
		DependencyIndexes: file_command_proto_depIdxs,
		EnumInfos:         file_command_proto_enumTypes,
		MessageInfos:      file_command_proto_msgTypes,
	}.Build()
	File_command_proto = out.File
	file_command_proto_goTypes = nil
	file_command_proto_depIdxs = nil
}
