user:
  instanceName: "User Type"
  database: users
  collection: m_user
  truncateIndex: true
  data:
    _id: id
    first_name: firstName
    last_name : lastName
    username: username
  # filter:
  #   isDeleted: false
  sort:
    createdAt: -1


