InstanceNameToBeSetInEnvVar1:
  instanceName: just an identifier, has no real use
  database: DatabaseName
  collection: CollectionName
  data:
    fieldNameInEs1: fieldNameinMongo1
    fieldNameInEs2: fieldNameinMongo2
    fieldNameInEs3: fieldNameinMongo3
  filter:
    fieldNameinMongo1: filterValue(acc to mongo docs)
  sort:
    fieldNameinMongo1: sortValue(acc to mongo docs)
InstanceNameToBeSetInEnvVar2:
  instanceName: just an identifier, has no real use
  database: DatabaseName
  collection: CollectionName
  data:
    fieldNameInEs1: fieldNameinMongo1
    fieldNameInEs2: fieldNameinMongo2
    fieldNameInEs3: fieldNameinMongo3
  filter:
    fieldNameinMongo1: filterValue(acc to mongo docs)
  sort:
    fieldNameinMongo1: sortValue(acc to mongo docs)
InstanceNameToBeSetInEnvVarN:
  instanceName: just an identifier, has no real use
  database: DatabaseName
  collection: CollectionName
  data:
    fieldNameInEs1: fieldNameinMongo1
    fieldNameInEs2: fieldNameinMongo2
    fieldNameInEs3: fieldNameinMongo3
  filter:
    fieldNameinMongo1: filterValue(acc to mongo docs)
  sort:
    fieldNameinMongo1: sortValue(acc to mongo docs)
