user:
  instanceName: people
  database: users
  collection: m_user
  data:
    _id: id
    firstName: first_name
    lastName: last_name
    about: about
    email: email
    address: address
    company: company
    username: username
  sort:
    createdAt: 1
post:
  instanceName: insight
  database: Post
  collection: m_post
  data:
    _id: id
    title: title
    description: description
circle:
  instanceName: circle
  database: Circle
  collection: m_circle
  data:
    _id: id
    circleName: circle_name
    description: description
    organization: organization
soapbox:
  instanceName: soapbox
  database: SoapBox
  collection: m_soapbox
  data:
    _id: id
    title: title
    description: description
byte:
  instanceName: byte
  database: Byte
  collection: m_byte
  data:
    _id: id
    title: title
    description: description
playlist:
  instanceName: list
  database: Playlist
  collection: m_play_post_mapping
  data:
    _id: id
    name: title
