name: Build Binaries
permissions:
  contents: read
  actions: write
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master]

jobs:
  build:
    if: |
      contains(github.event.head_commit.message, '[build]') ||
      contains(github.event.pull_request.title, '[build]')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64
            ext: .exe
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Get Version Info
        id: version
        run: |
          VERSION=$(git describe --tags --always --dirty)
          COMMIT=$(git rev-parse --short HEAD)
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit=$COMMIT" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
      
      - name: Build Binary
        run: |
          BINARY_NAME="wire-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}"
          echo "Building $BINARY_NAME..."
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} \
            go build -ldflags="-s -w \
              -X github.com/tarungka/wire/internal/cmd.Version=${{ steps.version.outputs.version }} \
              -X github.com/tarungka/wire/internal/cmd.Commit=${{ steps.version.outputs.commit }} \
              -X github.com/tarungka/wire/internal/cmd.Buildtime=${{ steps.version.outputs.date }}" \
            -o "$BINARY_NAME" ./cmd/.
          
          # Verify binary was created
          ls -lah wire-*
          
          # Create checksums
          sha256sum "$BINARY_NAME" > "$BINARY_NAME.sha256"
      
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: wire-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            wire-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}
            wire-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}.sha256
          retention-days: 7
      
      - name: Build Summary
        run: |
          echo "### Build Complete: ${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_STEP_SUMMARY
          echo "- Version: ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          echo "- Commit: ${{ steps.version.outputs.commit }}" >> $GITHUB_STEP_SUMMARY
          echo "- Binary: wire-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}" >> $GITHUB_STEP_SUMMARY